# Setup
title: JayCoding's Learning Record Blog
tagline: Constantly Learning!
baseurl: ""
paginate: 1
locale: "en"

# About/contact
author:
  name: Hyukjoo Lee
  url: http://hyukjoo-lee.github.io

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
